### ISSUE TITLE
Bootstrap: Beim --init geht das Logging nicht

### ISSUE THREAD

**Issue by turkishmaid** [turkishmaid/luechenbresse#4]
```
$ luechenbresse --init
Traceback (most recent call last):
  File .../bin/luechenbresse", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File ".../bin/luechenbresse", line 60, in <module>
    LogManager()
  File ".../luechenbresse/luechenbresse/dotfolder.py", line 108, in __new__
    rfh = logging.handlers.RotatingFileHandler(log_file, maxBytes=100_000, backupCount=10)
```

weil 

```python
class LogManager(object):
    def __new__(cls):
        if not hasattr(cls, 'instance') or not cls.instance:
            log_file = Path(os.environ["HOME"]) / ".luechenbresse" / "default.log"
```

:D

**Comment by turkishmaid** [comment]
Gefixt mit https://github.com/turkishmaid/luechenbresse/commit/eaa55a553709ef5e75d021752c052ee0bee10fb8
(da war der Typo jetzt wohl an der falschen Stelle :)
